import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { hashPassword, verifyPassword } from "@/lib/password";
import { getSessionUserId, setSessionCookie, clearSessionCookie } from "@/lib/session";

// One file handles account sign-up, username/password login, logout, and
// "who am I" -- same catch-all-path trick used for /api/webauthn.

export async function GET() {
  const userId = await getSessionUserId();
  if (!userId) return NextResponse.json({ user: null });
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: { id: true, username: true, name: true, isAdmin: true, active: true },
  });
  // A deactivated account's session cookie still passes middleware's
  // signature check (it can't reach Postgres to know better -- see
  // lib/access.ts) -- treating it as "no user" here is what actually
  // bounces them to /login (see the useEffect in app/page.tsx).
  if (!user || !user.active) return NextResponse.json({ user: null });
  return NextResponse.json({
    user: { id: user.id, username: user.username, name: user.name, isAdmin: user.isAdmin },
  });
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ action?: string[] }> }) {
  const { action } = await ctx.params;
  const step = action?.[0];

  if (step === "register") {
    const body = await req.json().catch(() => ({}));
    const username = String(body.username || "").trim().toLowerCase();
    const password = String(body.password || "");
    const name = String(body.name || "").trim() || null;
    const code = String(body.code || "").trim().toUpperCase();

    if (!username || !password || !code) {
      return NextResponse.json({ error: "Username, password, and invite code are required." }, { status: 400 });
    }
    if (password.length < 4) {
      return NextResponse.json({ error: "Password must be at least 4 characters." }, { status: 400 });
    }

    // One-time codes generated by an admin from /admin -- see
    // lib/access.ts. Replaces the old REGISTER_CODE env var (a single
    // code shared by everyone, with no way to revoke just one person).
    const invite = await prisma.accessCode.findUnique({ where: { code } });
    if (!invite || invite.revoked || invite.usedAt) {
      return NextResponse.json({ error: "That invite code is invalid or has already been used." }, { status: 403 });
    }

    const existing = await prisma.user.findUnique({ where: { username } });
    if (existing) {
      return NextResponse.json({ error: "That username is already taken." }, { status: 409 });
    }

    const user = await prisma.user.create({
      data: { username, name, passwordHash: hashPassword(password) },
    });

    await prisma.accessCode.update({
      where: { id: invite.id },
      data: { usedAt: new Date(), usedById: user.id },
    });

    await setSessionCookie(user.id);
    return NextResponse.json({
      ok: true,
      user: { id: user.id, username: user.username, name: user.name, isAdmin: user.isAdmin },
    });
  }

  if (step === "login") {
    const body = await req.json().catch(() => ({}));
    const username = String(body.username || "").trim().toLowerCase();
    const password = String(body.password || "");

    if (!username || !password) {
      return NextResponse.json({ error: "Username and password are required." }, { status: 400 });
    }

    const user = await prisma.user.findUnique({ where: { username } });
    if (!user || !user.active || !verifyPassword(password, user.passwordHash)) {
      return NextResponse.json({ error: "Incorrect username or password." }, { status: 401 });
    }

    await setSessionCookie(user.id);
    return NextResponse.json({
      ok: true,
      user: { id: user.id, username: user.username, name: user.name, isAdmin: user.isAdmin },
    });
  }

  if (step === "logout") {
    await clearSessionCookie();
    return NextResponse.json({ ok: true });
  }

  return NextResponse.json({ error: "Unknown action." }, { status: 404 });
}
